server:
  port: 56020

spring:
  application:
    name: app-consumer
  cloud:
    nacos:
      # 服务发现
      discovery:
      # 消费者发现的地址
        server-addr: 127.0.0.1:8848
#logging:
#  level:
#    root: info
#    org.springframework: info
